# Uncomment the next line to define a global platform for your project
 platform :ios, '12.2'

target 'RecipeBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecipeBook
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'HCSStarRatingView', '~> 1.5'
  pod 'GrowingTextView', '0.7.1'
  pod 'SideMenuSwift'
  pod 'JJFloatingActionButton'
  pod 'PopupDialog', '~> 1.1'
end
